# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  app:
    image: 211125402309.dkr.ecr.eu-west-3.amazonaws.com/isebastienstore:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/simpleCiCdApp
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test: [ CMD, curl, -f, http://localhost:8080/management/health ]
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    command: ["java", "-jar", "/app/myapp.jar"]  # Exemple de commande pour remplacer la commande par défaut
    restart: unless-stopped  # Politique de redémarrage
    pull_policy: always

  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb

  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
